# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{storage}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-06-17}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "lib/storage.rb",
     "lib/storage/config.rb",
     "lib/storage/errors.rb",
     "lib/storage/strategies.rb",
     "lib/storage/strategies/file_system.rb",
     "lib/storage/strategies/s3.rb",
     "lib/storage/version.rb",
     "spec/resources/file.txt",
     "spec/spec_helper.rb",
     "spec/storage/config_spec.rb",
     "spec/storage/strategies/file_system_spec.rb",
     "spec/storage/strategies/s3_spec.rb",
     "spec/storage_spec.rb"
  ]
  s.homepage = %q{http://github.com/fnando/storage}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{This gem provides a simple API for multiple storage backends. Supported storages: Amazon S3 and FileSystem.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/storage/config_spec.rb",
     "spec/storage/strategies/file_system_spec.rb",
     "spec/storage/strategies/s3_spec.rb",
     "spec/storage_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
    else
      s.add_dependency(%q<aws-s3>, [">= 0"])
    end
  else
    s.add_dependency(%q<aws-s3>, [">= 0"])
  end
end

